(define (problem harvest) 
(:domain harvest_planning)
(:objects 
    t1 - tractor
    f1 - farmer
    s1 s2 s3 s4 - soil
    farm - farm
    d1 - depot
    g1 - gas_station
    eggplant pumpkin - vegetable
    apple banana - fruit
)

(:init

    (tractor_at t1 farm)
    (farmer_at f1 farm)
    (=(free_capacity t1) 60)
    (=(carrying  eggplant t1) 0)
    (=(carrying apple t1) 0)
    (=(carrying banana t1) 0)
    (=(carrying pumpkin t1) 0)
    (=(demand_good eggplant) 27)
    (=(demand_good apple) 21)
    (=(demand_good banana) 10)
    (=(demand_good pumpkin) 9)
    (=(contain s1 apple)12)
    (=(contain s2 apple)14)
    (=(contain s3 apple)13)
    (=(contain s4 apple)0)
    (=(contain s1 banana)0)
    (=(contain s2 banana)0)
    (=(contain s3 banana)0)
    (=(contain s4 banana) 12)
    (=(contain s1 pumpkin)0)
    (=(contain s2 pumpkin)0)
    (=(contain s3 pumpkin)0)
    (=(contain s4 pumpkin) 11)
    (=(contain s1 eggplant)16)
    (=(contain s2 eggplant)17)
    (=(contain s3 eggplant)9)
    (=(contain s4 eggplant)0)
    (=(distance_km farm s1)11)
    (=(distance_km s1 farm)11)
    (=(distance_km s1 s2)9)
    (=(distance_km s2 s1)9)
    (=(distance_km s1 s3)8)
    (=(distance_km s3 s1)8)
    (=(distance_km s1 g1)7)
    (=(distance_km g1 s1)7)
    (=(distance_km s2 d1)15)
    (=(distance_km d1 s2)15) 
    (=(distance_km d1 s4)11) 
    (=(distance_km s4 d1)11)
    (=(distance_km s4 s2)13) 
    (=(distance_km s2 s4)13)  
    (=(max_fuel t1) 100)
    (=(left_fuel t1) 40)
    (=(consume_per_km t1) 1.5)
    (=(good_at_depot apple d1) 0)
    (=(good_at_depot eggplant d1) 0)
    (=(good_at_depot banana d1) 0)
    (=(good_at_depot pumpkin d1) 0)
    (linked farm s1)
    (linked s1 farm)
    (linked s1 s2)
    (linked s2 s1)
    (linked s1 s3)
    (linked s3 s1)
    (linked s1 g1)
    (linked g1 s1)
    (linked s2 d1)
    (linked d1 s2)
    (linked s4 d1)
    (linked d1 s4)
    (linked s2 s4)
    (linked s4 s2)
    (=(total_path) 0)
)

(:goal (and
    (=(good_at_depot eggplant d1) 27)
    (=(good_at_depot apple d1 ) 21)
    (=(good_at_depot banana d1) 10)
    (=(good_at_depot pumpkin d1) 9)
    )

    )

(:metric minimize (total_path))
)
